from fastapi import status

from ..src.schemas.user import UserSchema


def test_get_token(test_app, userdb_fixture):
    """
    Unit test for token generated by user authentication
    """

    # HTTP headers and data
    headers = {
        "accept": "application/json",
        "Content-Type": "application/x-www-form-urlencoded",
    }
    data = {
        "username": "admin",
        "password": "admin",
    }

    # Endpoint to be tested
    response = test_app.post("/token", headers=headers, data=data)

    # Validate asserts
    assert response.status_code == status.HTTP_200_OK
    assert "access_token" in response.json().keys()
    assert "token_type" in response.json().keys()


def test_users_me(test_app, userdb_fixture):
    # HTTP headers and data
    headers = {
        "accept": "application/json",
        "Content-Type": "application/x-www-form-urlencoded",
    }
    data = {
        "username": "admin1",
        "password": "admin",
    }

    # Endpoint to be tested
    response = test_app.post("/token", headers=headers, data=data)

    # Validate asserts
    assert response.status_code == status.HTTP_200_OK
    assert "access_token" in response.json().keys()
    assert "token_type" in response.json().keys()

    # HTTP headers
    headers = {
        "accept": "application/json",
        "Authorization": f"{response.json()['token_type']} {response.json()['access_token']}",
    }

    # Endpoint to be tested
    response = test_app.get("/auth/users/me", headers=headers)

    assert response.status_code == status.HTTP_200_OK
    assert UserSchema(**response.json()) is not None
